### ISSUE TITLE
Crash only when debugging

### ISSUE THREAD

**Issue by gcapes** [gcapes/training-course-feedback#3]
In the `analysis` directory, if I run `training_feedback.py` from a prompt, it runs fine. However, if I want to debug the script in pycharm, it crashes with the error below. Why is this? 

```
/home/mbexegc2/Documents/training/training-course-feedback/analysis/venv/bin/python /home/mbexegc2/pycharm-2021.1.2/plugins/python/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 40079 --file /home/mbexegc2/Documents/training/training-course-feedback/analysis/training_feedback.py
/home/mbexegc2/pycharm-2021.1.2/plugins/python/helpers/pydev/pydevd.py:1844: DeprecationWarning: currentThread() is deprecated, use current_thread() instead
  dummy_thread = threading.currentThread()
Connected to pydev debugger (build 212.4746.96)
Traceback (most recent call last):
  File "/home/mbexegc2/Documents/training/training-course-feedback/analysis/venv/lib/python3.10/site-packages/numpy/core/getlimits.py", line 384, in __new__
    dtype = numeric.dtype(dtype)
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mbexegc2/pycharm-2021.1.2/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/mbexegc2/pycharm-2021.1.2/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/mbexegc2/Documents/training/training-course-feedback/analysis/training_feedback.py", line 110, in <module>
    course_rating_by_faculty(data)
  File "/home/mbexegc2/Documents/training/training-course-feedback/analysis/training_feedback.py", line 24, in course_rating_by_faculty
    ax = data.groupby('faculty').rating.value_counts(normalize=True).unstack().T.sort_index().plot(kind='bar', rot=0, title='Rating')
  File "/home/mbexegc2/Documents/training/training-course-feedback/analysis/venv/lib/python3.10/site-packages/pandas/plotting/_core.py", line 972, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
  File "/home/mbexegc2/Documents/training/training-course-feedback/analysis/venv/lib/python3.10/site-packages/pandas/plotting/_matplotlib/__init__.py", line 71, in plot
    plot_obj.generate()
  File "/home/mbexegc2/Documents/training/training-course-feedback/analysis/venv/lib/python3.10/site-packages/pandas/plotting/_matplotlib/core.py", line 294, in generate
    self._post_plot_logic_common(ax, self.data)
  File "/home/mbexegc2/Documents/training/training-course-feedback/analysis/venv/lib/python3.10/site-packages/pandas/plotting/_matplotlib/core.py", line 473, in _post_plot_logic_common
    self._apply_axis_properties(ax.xaxis, rot=self.rot, fontsize=self.fontsize)
  File "/home/mbexegc2/Documents/training/training-course-feedback/analysis/venv/lib/python3.10/site-packages/pandas/plotting/_matplotlib/core.py", line 561, in _apply_axis_properties
    labels = axis.get_majorticklabels() + axis.get_minorticklabels()
  File "/home/mbexegc2/Documents/training/training-course-feedback/analysis/venv/lib/python3.10/site-packages/matplotlib/axis.py", line 1184, in get_majorticklabels
    ticks = self.get_major_ticks()
  File "/home/mbexegc2/Documents/training/training-course-feedback/analysis/venv/lib/python3.10/site-packages/matplotlib/axis.py", line 1355, in get_major_ticks
    numticks = len(self.get_majorticklocs())
  File "/home/mbexegc2/Documents/training/training-course-feedback/analysis/venv/lib/python3.10/site-packages/matplotlib/axis.py", line 1260, in get_majorticklocs
    return self.major.locator()
  File "/home/mbexegc2/Documents/training/training-course-feedback/analysis/venv/lib/python3.10/site-packages/matplotlib/ticker.py", line 2263, in __call__
    vmin, vmax = self.axis.get_view_interval()
  File "/home/mbexegc2/Documents/training/training-course-feedback/analysis/venv/lib/python3.10/site-packages/matplotlib/axis.py", line 1989, in getter
    return getattr(getattr(self.axes, lim_name), attr_name)
  File "/home/mbexegc2/Documents/training/training-course-feedback/analysis/venv/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 782, in viewLim
    self._unstale_viewLim()
  File "/home/mbexegc2/Documents/training/training-course-feedback/analysis/venv/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 778, in _unstale_viewLim
    self.autoscale_view(scalex=scalex, scaley=scaley)
  File "/home/mbexegc2/Documents/training/training-course-feedback/analysis/venv/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 2753, in autoscale_view
    handle_single_axis(
  File "/home/mbexegc2/Documents/training/training-course-feedback/analysis/venv/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 2716, in handle_single_axis
    x0, x1 = locator.nonsingular(x0, x1)
  File "/home/mbexegc2/Documents/training/training-course-feedback/analysis/venv/lib/python3.10/site-packages/matplotlib/ticker.py", line 1763, in nonsingular
    return mtransforms.nonsingular(v0, v1, expander=.05)
  File "/home/mbexegc2/Documents/training/training-course-feedback/analysis/venv/lib/python3.10/site-packages/matplotlib/transforms.py", line 2840, in nonsingular
    if maxabsvalue < (1e6 / tiny) * np.finfo(float).tiny:
  File "/home/mbexegc2/Documents/training/training-course-feedback/analysis/venv/lib/python3.10/site-packages/numpy/core/getlimits.py", line 387, in __new__
    dtype = numeric.dtype(type(dtype))
TypeError: 'NoneType' object is not callable
python-BaseException

Process finished with exit code 1

```

**Comment by gcapes** [comment]
This was using python 3.10. It doesn't happen with python 3.9.
